# Generated by Django 4.0.1 on 2022-01-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_body_weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelbodyweight',
            table='bodyweight',
        ),
    ]
